include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore

rules:
  prefer_const_constructors: false
  avoid_print: false
  prefer_typing_uninitialized_variables: false
  prefer_const_constructors_in_immutables: false